// a concrete tie in exact arithmetic that floating point resolves the wrong way, with the expression of f13cded's selectPiece
const rule = (lens, from, to) => { const len = (a, b) => lens.slice(a, b + 1).reduce((x, y) => x + y, 0), total = len(0, lens.length - 1); return { wrapLen: total - len(from + 1, to - 1), insideLen: len(from, to), wraps: total - len(from + 1, to - 1) < len(from, to) }; };
const found = [];
// a symmetrical oval-like lap: two straights and two turns, p1 == p3 (the turns), select the two straights p0 and p2: inside p0..p2, wrap p2..p3,p0: equal
for (const [a, b] of [[300, 282.7433], [300.1, 282.7433], [250.5, 314.1593], [120.3, 99.9], [100.1, 100.2], [333.3, 111.1]]) { const lens = [a, b, a, b]; const r = rule(lens, 0, 2); found.push({ lens, from: 0, to: 2, ...r, exactTie: Math.round((a + b + a) * 1e4) === Math.round((a + b + a + b - b) * 1e4) }); }
for (const f of found) console.log(JSON.stringify(f));
// random: print the first few exact ties (tenths of a metre) that floating point resolves as a WRAP
let shown = 0; for (let t = 0; t < 200000 && shown < 3; t++) { const m = 4 + Math.floor(Math.random() * 4), lens = Array.from({ length: m }, () => Math.round((60 + Math.random() * 300) * 10) / 10), from = Math.floor(Math.random() * (m - 2)), to = from + 2 + Math.floor(Math.random() * (m - from - 2)); if (to >= m) continue; const T = lens.map((v) => Math.round(v * 10)), sum = (x, y) => T.slice(x, y + 1).reduce((p, q) => p + q, 0); if (sum(from, to) === sum(0, m - 1) - sum(from + 1, to - 1) && rule(lens, from, to).wraps) { console.log('EXACT TIE taken across the line:', JSON.stringify({ lens, from, to, ...rule(lens, from, to) })); shown++; } }
// DETERMINISTIC: the case the hand-back quotes. Exact arithmetic (tenths of a metre): inside p2..p4 = 170.3 + 327.7 + 257.4 = 755.4; the other way = 327.7 + 170.3 + 327.7 + 257.4 - 327.7 = 755.4: a tie
{ const lens = [327.7, 170.3, 327.7, 257.4], r = rule(lens, 1, 3), T = lens.map((v) => Math.round(v * 10)), s = (a, b) => T.slice(a, b + 1).reduce((x, y) => x + y, 0); console.log('DETERMINISTIC', JSON.stringify({ lens, from: 1, to: 3, insideTenths: s(1, 3), wrapTenths: s(0, 3) - s(2, 2), ...r })); if (!(s(1, 3) === s(0, 3) - s(2, 2) && r.wraps)) { console.error('the quoted case did not reproduce'); process.exit(1); } }
